ibmcloud_api_key    = "YOUR_API_KEY"
ibmcloud_generation = "1"
ibmcloud_region     = "us-south"
ibmcloud_zone       = "us-south-1"

vpc_name            = "demo-vpc"
subnet_name         = "demo-subnet"
vm_name             = "demo-vm"
image_id            = "cfdaf1a0-5350-4350-fcbc-97173b510843"
profile_id          = "bc1-2x8"
network_port_speed  = "1000"
public_key_id       = "YOUR_PUBLIC_KEY_ID"
floating_ip_name    = "demo-fip"
